# Generated by Django 3.2.25 on 2025-06-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
