# Generated by Django 3.2.25 on 2025-06-28 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='score',
        ),
    ]
