# Generated by Django 4.2 on 2025-07-02 02:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_afkkst', max_length=255, null=True, verbose_name='image'),
        ),
    ]
