# Generated by Django 3.2.25 on 2025-06-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='level',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
